#!/bin/bash

#set -x
# Function to run the Maven command inside the Docker container
mrun() {
    # Initialize an array to hold directive names
    local directives=()
    local non_directives=()
    local interactive_flag="-it"  # Default to interactive mode

    # Loop through all provided arguments
    for arg in "$@"; do
        if [[ $arg == --* ]]; then
            # If the argument is a directive, add it to the array
            directives+=("$arg")
        else
            non_directives+=("$arg")
            # If it's not a directive, break out of the loop
            #break
        fi
    done

    # Shift the processed arguments
    set -- "${non_directives[@]}" # Retain only the non-directive arguments for the command

    output=""
    exit_code=1
    # Check for the --noit directive
    if [[ " ${directives[@]} " =~ " --noit " ]]; then
        # Capture the output of the Docker command
        set -x
        output=$(docker exec  maven mvn -f EventManagementApp/EventManApp "$@" $exec_cmd)
        set +x
        exit_code=$?
    else
        set -x
        docker exec -it maven mvn -f EventManagementApp/EventManApp "$@" $exec_cmd
        set +x
        exit_code=$?
    fi

    # Print the output if the exit code is not 0
    if [ $exit_code -ne 0 ]; then
        echo "Error running Docker command:"
        echo "$output"
    elif [[ ! " ${directives[@]} " =~ " --quiet " ]]; then
        # If --quiet is not present, print the output anyway
        echo "$output"
    fi

    # Return the exit status
    return $exit_code
}

mvn(){
    mrun "$@"
    return $?
}

mstatus() {
    # Initialize an array to hold directive names
    local directives=()
    local non_directives=()
    local interactive_flag="-it"  # Default to interactive mode

    # Loop through all provided arguments
    for arg in "$@"; do
        if [[ $arg == --* ]]; then
            # If the argument is a directive, add it to the array
            directives+=("$arg")
        else
            non_directives+=("$arg")
            # If it's not a directive, break out of the loop
            #break
        fi
    done

    # Shift the processed arguments
    set -- "${non_directives[@]}" # Retain only the non-directive arguments for the command

    exit_code=1
    # Check if Docker is running and if the container exists
    if [ "$(docker ps -q -f name=maven)" ]; then
        echo "Docker container 'maven' is available."
        # Display container short info
        # Capture the output of the Docker command
        output=$(docker inspect --format='{{.Name}} - {{.State.Status}}' maven)
        exit_code=$?
    elif [[ ! " ${directives[@]} " =~ " --quiet " ]]; then
        # If --quiet is not present, print the output anyway
        echo "$output"
    fi

    # Print the output if the exit code is not 0
    if [ $exit_code -ne 0 ]; then
        echo "Docker container 'maven' is not running or does not exist."
        echo "Error running Docker command:"
        echo "$output"
    fi

    # Return the exit status
    return $exit_code
}

mstatus
mavenStatus=$?

# Main code block
#if [ "$0" = "$BASH_SOURCE" ]; then
if [ "$0" = "./mavenrun" ] || [ "$0" = "mavenrun" ]; then
    if [ "$mavenStatus" -eq 0 ]; then
        # Run the mrun function with any additional arguments passed to the script
        mrun "$@"
        commandStatus=$?  # Capture the exit status of mrun
        exit "$commandStatus"  # Exit with the status of mrun
    else
        exit 1
    fi
fi
